### ISSUE TITLE
different from its results

### ISSUE THREAD

**Issue by FlyStory** [jolemon/FineLocator#2]
Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by jolemon** [comment]
Hi FlyStory,
Can you tell me in detail what is different between your results and its results?


As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version.


By the way, I found a bug in my code which is still not fixed: &nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting.

发自我的iPhone


------------------ Original ------------------
From: FlyStory ***@***.***&gt;
Date: Wed,Jun 9,2021 7:07 AM
To: jolemon/FineLocator ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [jolemon/FineLocator] different from its results (#2)





 
Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by FlyStory** [comment]
Hi&nbsp;jolemon,
&nbsp; &nbsp;&nbsp;I tried to reproduce the experiment of the paper, but I did not find the code at the time, so I collected the data set and rewritten the code according to the method in the paper, but found that there is a big difference with its results in AspectJ. I haven't found your code and data set at the time, so I want to ask you, is the result good on your data set and code? Can ***@***.*** exceed 20%? I downloaded your code is missing&nbsp;input.properties&nbsp;files when running.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 上午8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jolemon/FineLocator] different from its results (#2)





 Hi FlyStory, 
 Can you tell me in detail what is different between your results and its results? 
 
 
 As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version. 
 
 
 By the way, I found a bug in my code which is still not fixed: &amp;nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting. 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: FlyStory ***@***.***&amp;gt; 
 Date: Wed,Jun 9,2021 7:07 AM 
 To: jolemon/FineLocator ***@***.***&amp;gt; 
 Cc: Subscribed ***@***.***&amp;gt; 
 Subject: Re: [jolemon/FineLocator] different from its results (#2) 
 
 
 
 
 
   
 Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by jolemon** [comment]
Hi FlyStory,


作者的代码和数据集不是公开的。由于我在外旅行，我身边没有电脑，但我记得在我的数据集上运行我重现的代码效果都很差。此外，input.properties文件是记录run.sh文件中变量值的配置文件，因此我没有上传。



发自我的iPhone


------------------ Original ------------------
From: FlyStory ***@***.***&gt;
Date: Wed,Jun 9,2021 9:07 AM
To: jolemon/FineLocator ***@***.***&gt;
Cc: jolemon ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [jolemon/FineLocator] different from its results (#2)





 Hi&amp;nbsp;jolemon, 
 &amp;nbsp; &amp;nbsp;&amp;nbsp;I tried to reproduce the experiment of the paper, but I did not find the code at the time, so I collected the data set and rewritten the code according to the method in the paper, but found that there is a big difference with its results in AspectJ. I haven't found your code and data set at the time, so I want to ask you, is the result good on your data set and code? Can ***@***.*** exceed 20%? I downloaded your code is missing&amp;nbsp;input.properties&amp;nbsp;files when running. 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月9日(星期三) 上午8:53 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2) 
 
 
 
 
 
  Hi FlyStory,  
  Can you tell me in detail what is different between your results and its results?  
   
   
  As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version.  
   
   
  By the way, I found a bug in my code which is still not fixed: &amp;amp;nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting.  
   
  发自我的iPhone  
   
   
  ------------------ Original ------------------  
  From: FlyStory ***@***.***&amp;amp;gt;  
  Date: Wed,Jun 9,2021 7:07 AM  
  To: jolemon/FineLocator ***@***.***&amp;amp;gt;  
  Cc: Subscribed ***@***.***&amp;amp;gt;  
  Subject: Re: [jolemon/FineLocator] different from its results (#2)  
   
   
   
   
   
     
  Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by FlyStory** [comment]
Hi&nbsp;jolemon,
&nbsp; &nbsp;太棒了，可以讲中文，英文一直不是很好，还要翻译。不好意思，打扰了你的旅行。我在阅读论文的时候还发现了两个问题：（1）论文中时间邻近度拓展的计算方式和其假设好像并不一致，根据其计算公式，如果两个方法的修改时间越接近，那么计算出的结果是越小的。可是论文中的假设是，如果两个方法的修改时间越接近应该比修改时间更长的两个方法更接近。（2）论文中方法的最终向量化表示中，其计算公式并没有考虑方法原本的语义信息，并没有加上方法初始的向量化表示，仅仅有其拓展向量组成。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jolemon/FineLocator] different from its results (#2)





 Hi FlyStory, 
 
 
 作者的代码和数据集不是公开的。由于我在外旅行，我身边没有电脑，但我记得在我的数据集上运行我重现的代码效果都很差。此外，input.properties文件是记录run.sh文件中变量值的配置文件，因此我没有上传。 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: FlyStory ***@***.***&amp;gt; 
 Date: Wed,Jun 9,2021 9:07 AM 
 To: jolemon/FineLocator ***@***.***&amp;gt; 
 Cc: jolemon ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 Subject: Re: [jolemon/FineLocator] different from its results (#2) 
 
 
 
 
 
  Hi&amp;amp;nbsp;jolemon,  
  &amp;amp;nbsp; &amp;amp;nbsp;&amp;amp;nbsp;I tried to reproduce the experiment of the paper, but I did not find the code at the time, so I collected the data set and rewritten the code according to the method in the paper, but found that there is a big difference with its results in AspectJ. I haven't found your code and data set at the time, so I want to ask you, is the result good on your data set and code? Can ***@***.*** exceed 20%? I downloaded your code is missing&amp;amp;nbsp;input.properties&amp;amp;nbsp;files when running.  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月9日(星期三) 上午8:53  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2)  
   
   
   
   
   
   Hi FlyStory,   
   Can you tell me in detail what is different between your results and its results?   
     
     
   As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version.   
     
     
   By the way, I found a bug in my code which is still not fixed: &amp;amp;amp;nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting.   
     
   发自我的iPhone   
     
     
   ------------------ Original ------------------   
   From: FlyStory ***@***.***&amp;amp;amp;gt;   
   Date: Wed,Jun 9,2021 7:07 AM   
   To: jolemon/FineLocator ***@***.***&amp;amp;amp;gt;   
   Cc: Subscribed ***@***.***&amp;amp;amp;gt;   
   Subject: Re: [jolemon/FineLocator] different from its results (#2)   
     
     
     
     
     
       
   Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by jolemon** [comment]
问题1我没有注意到，所以当时只是按照原文公式实现了；问题2我咨询过作者，是英文论文中誊抄时候漏掉了，应该包含原有向量。

发自我的iPhone


------------------ Original ------------------
From: FlyStory ***@***.***&gt;
Date: Wed,Jun 9,2021 9:24 AM
To: jolemon/FineLocator ***@***.***&gt;
Cc: jolemon ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [jolemon/FineLocator] different from its results (#2)





 Hi&amp;nbsp;jolemon, 
 &amp;nbsp; &amp;nbsp;太棒了，可以讲中文，英文一直不是很好，还要翻译。不好意思，打扰了你的旅行。我在阅读论文的时候还发现了两个问题：（1）论文中时间邻近度拓展的计算方式和其假设好像并不一致，根据其计算公式，如果两个方法的修改时间越接近，那么计算出的结果是越小的。可是论文中的假设是，如果两个方法的修改时间越接近应该比修改时间更长的两个方法更接近。（2）论文中方法的最终向量化表示中，其计算公式并没有考虑方法原本的语义信息，并没有加上方法初始的向量化表示，仅仅有其拓展向量组成。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月9日(星期三) 上午9:16 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2) 
 
 
 
 
 
  Hi FlyStory,  
   
   
  作者的代码和数据集不是公开的。由于我在外旅行，我身边没有电脑，但我记得在我的数据集上运行我重现的代码效果都很差。此外，input.properties文件是记录run.sh文件中变量值的配置文件，因此我没有上传。  
   
   
   
  发自我的iPhone  
   
   
  ------------------ Original ------------------  
  From: FlyStory ***@***.***&amp;amp;gt;  
  Date: Wed,Jun 9,2021 9:07 AM  
  To: jolemon/FineLocator ***@***.***&amp;amp;gt;  
  Cc: jolemon ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;  
  Subject: Re: [jolemon/FineLocator] different from its results (#2)  
   
   
   
   
   
   Hi&amp;amp;amp;nbsp;jolemon,   
   &amp;amp;amp;nbsp; &amp;amp;amp;nbsp;&amp;amp;amp;nbsp;I tried to reproduce the experiment of the paper, but I did not find the code at the time, so I collected the data set and rewritten the code according to the method in the paper, but found that there is a big difference with its results in AspectJ. I haven't found your code and data set at the time, so I want to ask you, is the result good on your data set and code? Can ***@***.*** exceed 20%? I downloaded your code is missing&amp;amp;amp;nbsp;input.properties&amp;amp;amp;nbsp;files when running.   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年6月9日(星期三) 上午8:53   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2)   
     
     
     
     
     
    Hi FlyStory,    
    Can you tell me in detail what is different between your results and its results?    
       
       
    As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version.    
       
       
    By the way, I found a bug in my code which is still not fixed: &amp;amp;amp;amp;nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting.    
       
    发自我的iPhone    
       
       
    ------------------ Original ------------------    
    From: FlyStory ***@***.***&amp;amp;amp;amp;gt;    
    Date: Wed,Jun 9,2021 7:07 AM    
    To: jolemon/FineLocator ***@***.***&amp;amp;amp;amp;gt;    
    Cc: Subscribed ***@***.***&amp;amp;amp;amp;gt;    
    Subject: Re: [jolemon/FineLocator] different from its results (#2)    
       
       
       
       
       
         
    Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by FlyStory** [comment]
这篇论文是一名硕士研究生的毕业论文，我在知网上下载了他的毕业论文，仔细对照过，在他的毕业论文中方法最终向量化表示计算公式和英文论文是一样的，难道这也是誊抄错误？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月9日(星期三) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jolemon/FineLocator] different from its results (#2)





 问题1我没有注意到，所以当时只是按照原文公式实现了；问题2我咨询过作者，是英文论文中誊抄时候漏掉了，应该包含原有向量。 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------ 
 From: FlyStory ***@***.***&amp;gt; 
 Date: Wed,Jun 9,2021 9:24 AM 
 To: jolemon/FineLocator ***@***.***&amp;gt; 
 Cc: jolemon ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 Subject: Re: [jolemon/FineLocator] different from its results (#2) 
 
 
 
 
 
  Hi&amp;amp;nbsp;jolemon,  
  &amp;amp;nbsp; &amp;amp;nbsp;太棒了，可以讲中文，英文一直不是很好，还要翻译。不好意思，打扰了你的旅行。我在阅读论文的时候还发现了两个问题：（1）论文中时间邻近度拓展的计算方式和其假设好像并不一致，根据其计算公式，如果两个方法的修改时间越接近，那么计算出的结果是越小的。可是论文中的假设是，如果两个方法的修改时间越接近应该比修改时间更长的两个方法更接近。（2）论文中方法的最终向量化表示中，其计算公式并没有考虑方法原本的语义信息，并没有加上方法初始的向量化表示，仅仅有其拓展向量组成。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月9日(星期三) 上午9:16  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2)  
   
   
   
   
   
   Hi FlyStory,   
     
     
   作者的代码和数据集不是公开的。由于我在外旅行，我身边没有电脑，但我记得在我的数据集上运行我重现的代码效果都很差。此外，input.properties文件是记录run.sh文件中变量值的配置文件，因此我没有上传。   
     
     
     
   发自我的iPhone   
     
     
   ------------------ Original ------------------   
   From: FlyStory ***@***.***&amp;amp;amp;gt;   
   Date: Wed,Jun 9,2021 9:07 AM   
   To: jolemon/FineLocator ***@***.***&amp;amp;amp;gt;   
   Cc: jolemon ***@***.***&amp;amp;amp;gt;, Comment ***@***.***&amp;amp;amp;gt;   
   Subject: Re: [jolemon/FineLocator] different from its results (#2)   
     
     
     
     
     
    Hi&amp;amp;amp;amp;nbsp;jolemon,    
    &amp;amp;amp;amp;nbsp; &amp;amp;amp;amp;nbsp;&amp;amp;amp;amp;nbsp;I tried to reproduce the experiment of the paper, but I did not find the code at the time, so I collected the data set and rewritten the code according to the method in the paper, but found that there is a big difference with its results in AspectJ. I haven't found your code and data set at the time, so I want to ask you, is the result good on your data set and code? Can ***@***.*** exceed 20%? I downloaded your code is missing&amp;amp;amp;amp;nbsp;input.properties&amp;amp;amp;amp;nbsp;files when running.    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年6月9日(星期三) 上午8:53    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2)    
       
       
       
       
       
     Hi FlyStory,     
     Can you tell me in detail what is different between your results and its results?     
         
         
     As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version.     
         
         
     By the way, I found a bug in my code which is still not fixed: &amp;amp;amp;amp;amp;nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting.     
         
     发自我的iPhone     
         
         
     ------------------ Original ------------------     
     From: FlyStory ***@***.***&amp;amp;amp;amp;amp;gt;     
     Date: Wed,Jun 9,2021 7:07 AM     
     To: jolemon/FineLocator ***@***.***&amp;amp;amp;amp;amp;gt;     
     Cc: Subscribed ***@***.***&amp;amp;amp;amp;amp;gt;     
     Subject: Re: [jolemon/FineLocator] different from its results (#2)     
         
         
         
         
         
           
     Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.

**Comment by jolemon** [comment]
我的微信sincetonight ，在微信上说吧



发自我的iPhone


------------------ Original ------------------
From: FlyStory ***@***.***&gt;
Date: Wed,Jun 9,2021 9:39 AM
To: jolemon/FineLocator ***@***.***&gt;
Cc: jolemon ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [jolemon/FineLocator] different from its results (#2)





 这篇论文是一名硕士研究生的毕业论文，我在知网上下载了他的毕业论文，仔细对照过，在他的毕业论文中方法最终向量化表示计算公式和英文论文是一样的，难道这也是誊抄错误？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月9日(星期三) 上午9:35 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2) 
 
 
 
 
 
  问题1我没有注意到，所以当时只是按照原文公式实现了；问题2我咨询过作者，是英文论文中誊抄时候漏掉了，应该包含原有向量。  
   
  发自我的iPhone  
   
   
  ------------------ Original ------------------  
  From: FlyStory ***@***.***&amp;amp;gt;  
  Date: Wed,Jun 9,2021 9:24 AM  
  To: jolemon/FineLocator ***@***.***&amp;amp;gt;  
  Cc: jolemon ***@***.***&amp;amp;gt;, Comment ***@***.***&amp;amp;gt;  
  Subject: Re: [jolemon/FineLocator] different from its results (#2)  
   
   
   
   
   
   Hi&amp;amp;amp;nbsp;jolemon,   
   &amp;amp;amp;nbsp; &amp;amp;amp;nbsp;太棒了，可以讲中文，英文一直不是很好，还要翻译。不好意思，打扰了你的旅行。我在阅读论文的时候还发现了两个问题：（1）论文中时间邻近度拓展的计算方式和其假设好像并不一致，根据其计算公式，如果两个方法的修改时间越接近，那么计算出的结果是越小的。可是论文中的假设是，如果两个方法的修改时间越接近应该比修改时间更长的两个方法更接近。（2）论文中方法的最终向量化表示中，其计算公式并没有考虑方法原本的语义信息，并没有加上方法初始的向量化表示，仅仅有其拓展向量组成。   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年6月9日(星期三) 上午9:16   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2)   
     
     
     
     
     
    Hi FlyStory,    
       
       
    作者的代码和数据集不是公开的。由于我在外旅行，我身边没有电脑，但我记得在我的数据集上运行我重现的代码效果都很差。此外，input.properties文件是记录run.sh文件中变量值的配置文件，因此我没有上传。    
       
       
       
    发自我的iPhone    
       
       
    ------------------ Original ------------------    
    From: FlyStory ***@***.***&amp;amp;amp;amp;gt;    
    Date: Wed,Jun 9,2021 9:07 AM    
    To: jolemon/FineLocator ***@***.***&amp;amp;amp;amp;gt;    
    Cc: jolemon ***@***.***&amp;amp;amp;amp;gt;, Comment ***@***.***&amp;amp;amp;amp;gt;    
    Subject: Re: [jolemon/FineLocator] different from its results (#2)    
       
       
       
       
       
     Hi&amp;amp;amp;amp;amp;nbsp;jolemon,     
     &amp;amp;amp;amp;amp;nbsp; &amp;amp;amp;amp;amp;nbsp;&amp;amp;amp;amp;amp;nbsp;I tried to reproduce the experiment of the paper, but I did not find the code at the time, so I collected the data set and rewritten the code according to the method in the paper, but found that there is a big difference with its results in AspectJ. I haven't found your code and data set at the time, so I want to ask you, is the result good on your data set and code? Can ***@***.*** exceed 20%? I downloaded your code is missing&amp;amp;amp;amp;amp;nbsp;input.properties&amp;amp;amp;amp;amp;nbsp;files when running.     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "jolemon/FineLocator"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年6月9日(星期三) 上午8:53     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [jolemon/FineLocator] different from its results (#2)     
         
         
         
         
         
      Hi FlyStory,      
      Can you tell me in detail what is different between your results and its results?      
           
           
      As fas as I know, the IST dataset that they used in the paper is very different from the Defects4J dataset I used. They integrate all buggy methods in ONE code version and use FineLocator to locate buggy methods in this code version. In this way, the program will take much less time to run. However, I don’t think it’s the right, because bugs shouldn’t be in one code version.      
           
           
      By the way, I found a bug in my code which is still not fixed: &amp;amp;amp;amp;amp;amp;nbsp;in cal_MAP_MRR_Hit-K.sh, “sort -g” would be right instead of “sort -n”, considering scientific counting.      
           
      发自我的iPhone      
           
           
      ------------------ Original ------------------      
      From: FlyStory ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      Date: Wed,Jun 9,2021 7:07 AM      
      To: jolemon/FineLocator ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      Cc: Subscribed ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      Subject: Re: [jolemon/FineLocator] different from its results (#2)      
           
           
           
           
           
             
      Can I see the results of the experiment? I repeated the work of this paper and found that it was very different from its results.
